<?php

/**
* CategoryTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class CategoryTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object CategoryTable
    */
    static public function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    static public function getListQuery(Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getInstance()->createQuery('a');
        return $q;
    }
}