<?php

/**
* CategoryTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class CategoryTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object CategoryTable
    */
    static public function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    static public function getListQuery(Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getInstance()->createQuery('a');
        return $q;
    }
    
    public function findAll($culture = 'br', Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getListQuery();
        $alias = $q->getRootAlias();

        $q->leftJoin("{$alias}.Translation t")
            ->andWhere("t.lang = ?", $culture);

        return $q;
    }

    public function findOneBySlugAndCulture($slug, $culture = 'br', Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getListQuery();
        $alias = $q->getRootAlias();

        $q->leftJoin("{$alias}.Translation t")
            ->andWhere('t.lang = ?', $culture)
            ->andWhere('t.slug = ?', $slug);

        return $q;
    }
}