<?php

/**
* ProductTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class ProductTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object ProductTable
    */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }

    static public function getListQuery(Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getInstance()->createQuery('a');
        return $q;
    }

    public function findByCulture($culture = 'pt', Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getListQuery();
        $alias = $q->getRootAlias();

        $q->leftJoin("{$alias}.Translation t")
            ->andWhere('t.lang = ?', $culture);

        return $q;
    }

    public function findOneByRouteAndCulture($route, $culture = 'pt', Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getListQuery();
        $alias = $q->getRootAlias();

        $q->leftJoin("{$alias}.Translation t")
            ->andWhere("t.lang = ?", $culture)
            ->andWhere("{$alias}.slug_route = ?", $route);

        return $q;
    }

    //*
    public function getForLuceneQuery($query, $culture='pt', Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getListQuery();
        $alias = $q->getRootAlias();

        $hits = self::getLuceneIndex($culture)->find($query);

        $pks = array();
        foreach ($hits as $hit)
        {
            $pks[] = $hit->pk;
        }

        if (empty($pks))
        {
            return array();
        }

        $q->whereIn("{$alias}.id", $pks);
        return $q;
    }

    static public function getLuceneIndex($culture)
    {
        ProjectConfiguration::registerZend();
        if (file_exists($index = self::getLuceneIndexFile($culture))) return Zend_Search_Lucene::open($index);
        return Zend_Search_Lucene::create($index);
    }

    static public function getLuceneIndexFile($culture)
    {
        return sfConfig::get('sf_data_dir').'/product.'.sfConfig::get('sf_environment').'.'.$culture.'.index';
    }
    //*/
}