<?php

/**
* ProductTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class ProductTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object ProductTable
    */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }

    static public function getListQuery(Doctrine_Query $q = null)
    {
        if(null === $q)$q = static::getInstance()->createQuery('a');
        return $q;
    }
}