<?php

/**
* Product
* 
* This class has been auto-generated by the Doctrine ORM Framework
* 
* @package    sfI18nSample
* @subpackage model
* @author     Thiago Lagden
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
class Product extends BaseProduct
{
    //...
}