<?php

/**
* Product
* 
* This class has been auto-generated by the Doctrine ORM Framework
* 
* @package    sfI18nSample
* @subpackage model
* @author     Thiago Lagden
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
class Product extends BaseProduct
{
    //*
    public function save(Doctrine_Connection $conn = null)
    {
        // ...

        $conn = $conn ? $conn : $this->getTable()->getConnection();
        $conn->beginTransaction();
        try
        {
            $ret = parent::save($conn);

            $this->updateLuceneIndex();

            $conn->commit();

            return $ret;
        }
        catch (Exception $e)
        {
            $conn->rollBack();
            throw $e;
        }
    }

    public function updateLuceneIndex()
    {
        $tbl = $this->getTable();
        $index = $tbl::getLuceneIndex();

        // remove existing entries
        foreach ($index->find('pk:'.$this->getId()) as $hit)
        {
            $index->delete($hit->id);
        }

        // don't index expired and non-activated jobs
        // if ($this->isExpired() || !$this->getIsActivated())
        // {
        //     return;
        // }

        $doc = new Zend_Search_Lucene_Document();

        // store job primary key to identify it in the search results
        $doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));

        // index job fields
        $doc->addField(Zend_Search_Lucene_Field::UnStored('name', $this->getName(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('description', $this->getDescription(), 'utf-8'));

        // add job to the index
        $index->addDocument($doc);
        $index->commit();
    }

    public function delete(Doctrine_Connection $conn = null)
    {
        $tbl = $this->getTable();
        $index = $tbl::getLuceneIndex();

        foreach ($index->find('pk:'.$this->getId()) as $hit)
        {
            $index->delete($hit->id);
        }

        return parent::delete($conn);
    }
    //*/
}
