homepage:
  url:   /
  param: { module: home, action: index }

localized_homepage:
  url:   /:sf_culture
  param: { module: home, action: index }
  requirements:
    sf_culture: (?:pt|en)

change_language:
  url:   /change_language/:path
  param: { module: home, action: changeLanguage }

categoria_show:
  url:     /:sf_culture/categoria/:route.:sf_format
  param:   { module: home, action: showCategoria, sf_format: html }
  requirements:
    sf_format: (?:html|json)

produto_show:
  url:     /:sf_culture/produto/:route
  param:   { module: produto, action: show }

produto_search:
  url:   /:sf_culture/busca/:q
  param: { module: produto, action: search, q: null }

produto_fill:
  url:   /produto/fill
  param: { module: produto, action: fixtures}
