homepage:
  url:   /
  param: { module: home, action: index }

localized_homepage:
  url:   /:sf_culture/
  param: { module: home, action: index }
  requirements:
    sf_culture: (?:br|en)

change_language:
  url:   /change_language
  param: { module: home, action: changeLanguage }

categoria_show:
  url:     /:sf_culture/categoria/:slug.:sf_format
  param:   { module: home, action: showCategoria, sf_format: html }
  requirements:
    sf_format: (?:html|json)

produto_show:
  url:     /:sf_culture/produto/:slug
  param:   { module: produto, action: show }
