Category:
  actAs:
    Sluggable:
          fields: [route]
          name:  slug_route
          unique: true
          canUpdate: true
    Timestampable: ~
    I18n:
      fields: [name, description]
      length: 5
      actAs:
        Sluggable:
          fields: [name]
          uniqueBy: [lang, name]
          canUpdate: true
        SearchLucene:
          fields: [name, description]
  columns:
    route: { type: string(255), notnull: true }
    name: { type: string(255), notnull: true }
    description: clob

Product:
  actAs:
    Sluggable:
          fields: [route]
          name:  slug_route
          unique: true
          canUpdate: true
    Timestampable: ~
    I18n:
      length: 5
      fields: [name, description, price]
      actAs:
        Sluggable:
          fields: [name]
          uniqueBy: [lang, name]
          canUpdate: true
        SearchLucene:
          fields: [name, description, price]
  columns:
    route: { type: string(255), notnull: true }
    name: { type: string(255), notnull: true }
    description: clob
    price: { type: 'decimal(12, 2)', default: '0.00'}
    is_active: { type: boolean, default: 1 }
    category_id: bigint
  relations:
    Category:
      local: category_id
      class: Category
      foreignAlias: Products
      onDelete: 'SET NULL'